### ISSUE TITLE
Try Again button stays up when a new answer is given

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#101]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/294
In the publishe version of the sim and Fractions Equality, when you get a problem wrong the first time a try again button pops up.  If, instead of pressing it, you drag a new piece up it behaves as if you did press the button and gives you a new check button.  In the dev version the try again button does not go away.  You need to press it to continue.  If your new answer is already up when you do this a check button is not given and you need to move one of those two pieces to get it to appear.
**Steps to reproduce:**
1. Go to a level
2. Get an answer wrong
3. Without hitting try again, drag a different piece up to replace one of the answers
4. Note behavior and hit try again
5. Remove one of the pieces and put it back

**Screenshots:**
![tryagainbehavior](https://user-images.githubusercontent.com/41024075/53973308-c1724980-40bd-11e9-9b35-b5ffa18f562f.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fraction Matcher‬
URL: https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.10/phet/fraction-matcher_all_phet.html
Version: 1.2.0-dev.10 2019-03-05 17:13:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
I just noticed this as well. Ideally, if you drag up a new fraction without pressing try again, you should be prompted to check.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by KatieWoe** [comment]
Looks solved on master

**Comment by jonathanolson** [comment]
Thanks!
