### ISSUE TITLE
Size and placement issues of pointer areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#102]
For https://github.com/phetsims/QA/issues/294
I noticed on iPad that if you try to press the top of one of the levels on the bottom row, sometimes you'd go to the wrong level.  I checked pointer areas and saw that they extend far bellow the actual button, and if you press just above the intended button, you can hit the wrong thing by accident.
I also noticed the the touch area for the sound button is very expanded, but the touch area for the timer is not at all.  I think these should be the same either way.
![pointerareaoddities](https://user-images.githubusercontent.com/41024075/53978481-8f1a1980-40c8-11e9-9784-394ee775b006.jpg)

**Comment by amanda-phet** [comment]
I agree that these touch areas need to be revised. @jonathanolson can you adjust the areas for the level selection buttons to be the actual button? I don't think they need to be larger since these buttons are already large. 

Also, please adjust the timer/sound touch areas to be consistent.

**Comment by jonathanolson** [comment]
Done in the above commit.
