### ISSUE TITLE
Multitouch restart causes sim to freeze

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#105]
**Test device:**
Hopper
**Operating System:**
12.3.1
**Browser:**
safari
**Problem description:**
For https://github.com/phetsims/QA/issues/336
When dragging an object, clicking the orange reset button can cause the sim to freeze.  Happens on devices with touch screens.  This does seem to happen on the published sim.
**Steps to reproduce:**
1. Go to Equality Lab screen
2. Go to either the red or yellow bar scene (does not work on pie or water scenes)
3. Pick up a piece with one finger and hold it
4. With another finger, hit the orange reset button

**Screenshots:**
![freezingpage](https://user-images.githubusercontent.com/41024075/59067227-43fdd700-886e-11e9-8a8b-b80588ddd6d3.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fractions: Equality‬
URL: https://phet-dev.colorado.edu/html/fractions-equality/1.1.0-rc.1/phet/fractions-equality_all_phet.html
Version: 1.1.0-rc.1 2019-06-05 20:20:58 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
Should be patched in master and in the release branch.

@KatieWoe can you confirm this is fixed in master?

**Comment by KatieWoe** [comment]
Not fixed in master

**Comment by jonathanolson** [comment]
Confirmed fixed in master in person. I'll look into the other related problem with that issue. Thanks!
