### ISSUE TITLE
CT: Uncaught Error: Not a RangedProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fractions-common#115]
Related to  https://github.com/phetsims/scenery-phet/issues/740 and https://github.com/phetsims/fractions-common/issues/114...

CT is reporting this failure related to BeakerNode, for all sims in the fractions family

```
VM49138 NumberProperty.js:177 Uncaught Error: Not a RangedProperty
    at NumberProperty.asRanged (VM49138 NumberProperty.js:177:13)
    at new FractionsCommonBeakerNode (VM49677 FractionsCommonBeakerNode.js:40:30)
    at BeakerSceneNode.getIcon (VM49524 BeakerSceneNode.js:47:12)
    at new ContainerSetScreenView (VM49528 ContainerSetScreenView.js:60:29)
    at new EqualityLabScreenView (VM49186 EqualityLabScreenView.js:48:5)
    at EqualityLabScreen.name [as createView] (VM49129 EqualityLabScreen.js:19:50)
    at EqualityLabScreen.initializeView (VM49170 Screen.js:211:23)
    at Array.<anonymous> (VM49125 Sim.js:631:16)
    at VM49125 Sim.js:638:21
```

The problem was introduced in 34fe4ce1, in FractionsCommonBeakerNode.js:

```js
    const waterLevelProperty = new NumberProperty( numerator / denominator );
    super( waterLevelProperty.asRanged(), options );
```

Not all NumberProperty instances are "ranged".  In this case, waterLevelProperty is not a RangedProperty, because it was not instantiated with the `range` option.  

You'll need to add a range to `waterLevelProperty`, and I don't know what the appropriate range is for the fractions sims.

**Comment by pixelzoom** [comment]
I need to move forward with some cross-cutting changes, and this was getting in the way of local aqua testing.  So in the above commit, I added `range: new Range( 0, 1 )` to `waterLevelProperty`.  Fuzz testing didn't reveal any problems.  But please confirm with @jonathanolson (reponsible dev) that this is an appropriate range.

**Comment by pixelzoom** [comment]
I need to move forward with some cross-cutting changes, and this was getting in the way of local aqua testing.  So in the above commit, I added `range: new Range( 0, 1 )` to `waterLevelProperty`.  Fuzz testing didn't reveal any problems.  But please confirm with @jonathanolson (reponsible dev) that this is an appropriate range.

**Comment by marlitas** [comment]
Transferred the range question as a part of https://github.com/phetsims/fractions-common/issues/114, closing to consolidate issue.
