### ISSUE TITLE
Fraction can get out of sync with what is shown in the center area graphics

### ISSUE THREAD

**Issue by jbphet** [phetsims/fractions-common#120]
This is a multitouch issue that was discovered by CT and logged in https://github.com/phetsims/fractions-common/issues/112.  In the CT issue it is reported as an assertion, in the published sims it manifests as a mismatch between the graphics shown on the screen and the numerical depiction of the fraction.  This affects Fractions: Intro, Fractions: Mixed Numbers, Fractions: Equality, and possibly others in this suite of sims.  Here is a screenshot from the currently published version Fractions: Intro, which is version 1.0.24, that shows the problem:

![image](https://github.com/phetsims/fractions-common/assets/3082831/6a074ece-c874-4923-9412-8857e95dc942)

**Comment by jbphet** [comment]
Here is a video that shows how the issue can be reproduced:


https://github.com/phetsims/fractions-common/assets/3082831/09f4fd9d-682f-4490-bdd8-d00b1ed50741

**Comment by jbphet** [comment]
@jonathanolson and I were working on this bug together when we realized it impacts the published sims.  The big question is whether it warrants a maintenance release, so I'm going to ask on our Slack planning channel and will record the response here.

**Comment by jbphet** [comment]
Only @pixelzoom and @kathy-phet responded to my questing in the planning channel.  @pixelzoom said:

> That does seems like a pretty significant problem, unless you don’t think students are not using multitouch.  But my guess is that the younger the age group, the more little hands that will be simultaneously whacking away at the UI. So +1 for a maintenance.

@kathy-phet suggested considering turning off multi-touch for the sim, but I don't think that's necessary since we have a working solution and I'm not sure we even have the capability to turn it off.  She did not log an opinion on whether to prioritize a maintenance release for the fractions suite.

**Comment by jbphet** [comment]
I would estimate that doing this maintenance release would only take 1-2 hrs if everything went well, but more if we run into any complications with integrating the fractions-common change with each of the sims.

**Comment by jbphet** [comment]
I'm not clear on what to do next on this, and I don't think it rises to the level of being a Monday.com request, so I'm going to reassign it to the folks that are currently doing our iteration planning.  They can reassign as appropriate.

**Comment by marlitas** [comment]
I'll go ahead and make a request for this so we can talk about it at our weekly planning meeting. Thanks for doing the research and discovery work on this @jbphet!

**Comment by jbphet** [comment]
The word has come down that I should go ahead with a maintenance release for this, so I will.

**Comment by jbphet** [comment]
@jonathanolson and I just discussed the status of this issue and feel that since the pointer cancel fixes didn't clear up CT entirely, we should re-publish the affected sims with the workaround-ish fix.

**Comment by jbphet** [comment]
@jonathanolson and I have done a maintenance release on fractions-intro, fractions-mixed-numbers, and fractions-equality with a fix for this problem.  I'll check the published versions once the website caches have updated (typically about 24 hours).

**Comment by jbphet** [comment]
I've validated that the fixed versions are now available on out main site.  Closing.
