### ISSUE TITLE
Memory vs performance behavior

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#15]
Switching between game levels currently seems to lag a bit, even on "faster" platforms, since currently the sim needs to create a new view for the "new" challenge.

@ariel-phet can you see if this is enough of a performance issue (both on desktop and iOS) in your opinion?

For devices not limited by memory, I could create views for all of the levels. This would make startup/reset-all slightly slower, but would make switching between levels snappier. This is easy, but can't be done for memory-limited things like older iPads.

Alternatively, I can look at reworking views so that one view can switch between models (then I would only need two views, since animations show at most 2 at a time). This would involve more complexity in the code, but would speed up performance probably across-the-board (including memory-limited iPads).

https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.9/phet/build-a-fraction_en_phet.html (the previous dev release) is probably a good enough indicator for performance (testing both shape and number levels), and I'll have a dev release probably later tonight that I'll be able to link.

**Comment by ariel-phet** [comment]
@jonathanolson - to me desktop performance looks absolutely snappy.

iOS on iPad2 is laggy (but we will soon be dropping this platform as officially supported). It is usable, but a very obvious lag.

I will try to check on a newer iPad tomorrow. I am guessing it will look fine there, and not be worth any extra effort at the moment.

**Comment by ariel-phet** [comment]
@jonathanolson I checked on an iPad Air and things were perfectly snappy. 

Currently I feel it is not worth the effort to improve the iPad2 performance. It is a very obvious lag, but not unusable. 

Closing
