### ISSUE TITLE
Should "dragged" cake pieces be "over" cakes?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#16]
Currently when you drag a cake piece, it is always over all of the cakes:

![cake-drag-layering](https://user-images.githubusercontent.com/480878/49205932-adf06d80-f36d-11e8-865a-ae9bbca6300c.PNG)

This  makes sense to me, but looks weird. I'd like to do what is done for the shape types here and add a shadow behind dragged pieces, e.g.:

![fraction-shadow](https://user-images.githubusercontent.com/480878/49206058-117a9b00-f36e-11e8-82a4-b69865a90e65.PNG)

Alternatively we could adjust the z-order so that dragged pieces would look like they are sliding into the open space (correctly stacked). This option comes with some extra code complexity that I'm not excited  to tackle.

Thoughts?

**Comment by ariel-phet** [comment]
@jonathanolson I think a shadow would be a nice touch and would make it more clear that the piece being dragged is "in the air"

**Comment by jonathanolson** [comment]
Hmm, the shadow (when generated from the touch area) doesn't look too great to me:

![shadow-1](https://user-images.githubusercontent.com/480878/49558270-b42f9e00-f8c7-11e8-9cbb-0931adcd1802.PNG)
![shadow-2](https://user-images.githubusercontent.com/480878/49558278-b8f45200-f8c7-11e8-9612-e53f508d5378.PNG)

Maybe it would be possible for someone to take the cake images and create a shadow image (doesn't include the cake, just the shadow) for each one?

**Comment by jonathanolson** [comment]
Branch above for the current code if desired.

I think the "cheap" shadow works for the flat shapes because it's a flat thing where the shadow would be the exact same shape. Here the shadow would naturally be very different.

**Comment by amanda-phet** [comment]
>Maybe it would be possible for someone to take the cake images and create a shadow image (doesn't include the cake, just the shadow) for each one? 

This is basically what I did in Equality Explorer. Given the time crunch we are in, I think we should pick a different solution. 

I played with it a bit and compared with the java version and I think the current behavior isn't too bothersome and is still an improvement.

**Comment by jonathanolson** [comment]
@ariel-phet had the idea to just use the "base" of the cake slices for the shadows, and this looks much better to me.

Additionally, switching all of the shadows on the "intro" style screens to semi-transparent seems to improve the appearance.

@amanda-phet can you try out latest master (on phettest) to see how it looks to you?

**Comment by ariel-phet** [comment]
@jonathanolson @amanda-phet I really like the semitransparent shadow on the "intro" style screens on all the flat pieces.

I think it also looks pretty good on the cake pieces as well. All looking good in master to me.

**Comment by amanda-phet** [comment]
The cake looks fine to me. And I agree the semi-transparent shadow on other scenes works well.
