### ISSUE TITLE
Lab screen crashing on Chrome

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#2]
Chrome 66 macOS 10.13.4, Fractions Intro. Try to open the 3rd screen from the homescreen. Instant crash for me.

@lmulhall-phet, are you able to reproduce?

Chrome was crash earlier depending on the exact shape of a path, so I may need to experiment with workarounds...

**Comment by phet-steele** [comment]
@jonathanolson, as I said in so much expert detail with all the information you would ever need: https://github.com/phetsims/scenery/issues/750#issuecomment-376268020 😄. Same goes for this issue.

**Comment by lmulhall-phet** [comment]
@jonathanolson What version?

**Comment by phet-steele** [comment]
> @jonathanolson What version?

@lmulhall-phet master.

**Comment by lmulhall-phet** [comment]
@jonathanolson I am not able to reproduce.

**Comment by lmulhall-phet** [comment]
@jonathanolson, do we need to do anything else with this?

**Comment by jonathanolson** [comment]
I'll track it down.

Also... it doesn't seem to crash if I have devtools open... interesting.

**Comment by jonathanolson** [comment]
Can't reproduce now, closing.
