### ISSUE TITLE
Fractions Intro Game screen has challenges less than 1

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fractions-common#20]
So the empty fraction container should not show the plus sign in these instances. 

![image](https://user-images.githubusercontent.com/7852916/49539234-6d6f8300-f88a-11e8-8813-7ac9cc9a4078.png)

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by amanda-phet** [comment]
Looks like it is working well!
