### ISSUE TITLE
Mixed Numbers Lab screen should have mixed number container on startup

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fractions-common#21]
![image](https://user-images.githubusercontent.com/7852916/49539302-9132c900-f88a-11e8-8329-e48925ed00a5.png)

**Comment by jonathanolson** [comment]
Implemented.

For the Lab screen of build-a-fraction, what do you want? (It is the "mixed number" variety and shows the mixed number in the panel on the bottom). Tentatively it also starts out with a mixed number, but I can have it start with a non-mixed group.

**Comment by amanda-phet** [comment]
Mixed number is fine with me for the build-a-fraction sim. Thanks!
