### ISSUE TITLE
Lab screen pixel-polish

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fractions-common#22]
The spacing below the blue rectangles seems larger than above. However the spacing around the red circles seems fine.

![image](https://user-images.githubusercontent.com/7852916/49539370-bb848680-f88a-11e8-91af-680eacc564a5.png)

Can you shift the rectangles down a smidge?

**Comment by jonathanolson** [comment]
Should be fixed (both should have the same center for alignment), can you verify?

**Comment by amanda-phet** [comment]
Looks good to me!
