### ISSUE TITLE
have container controls go away on Game screens, like Lab screens

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fractions-common#23]
To be consistent with the Lab screen, let's hide the +/- and <> buttons when the container is not active/ in focus. 

![image](https://user-images.githubusercontent.com/7852916/49539518-0b634d80-f88b-11e8-970b-335d28f97b77.png)

If you answer a challenge correctly and a new container pops out into the play area, it will have focus. 

Happy to discuss this at design meeting since we did already make a conscious decision not to do this, but I think it will be nicer to be consistent between screens.

**Comment by jonathanolson** [comment]
Implemented. The "selected" status for groups should apply now to all game screens.

It selects the initial group and any groups that are animated out to the middle (for consistency).

Can you verify?

**Comment by amanda-phet** [comment]
All screens are looking good to me. Thanks!
