### ISSUE TITLE
Increase touch areas to improve phone use

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/fractions-common#28]
I was playing with the Fractions sims on my phone and experiencing some challennges. 

I think it would be good to review all the touchAreas and optimize them. In particular, the touchAreas on those controls in the "build container" that disappear when you tap away from the build container were particularly problematic because if I was trying to "undo" something but I missed the control, all the controls would disappear. See image here - I think we could increase these quite a bit without causing an issue. 

![image](https://user-images.githubusercontent.com/5096804/49668788-73956900-fa1c-11e8-8bd4-6dd64ee23fdd.png)

@amanda-phet - Can you take a pass through these sims and make recommendations for touch area sizes? Thanks! 

It seemed like all the draggable pieces were "swipe to drag" pickupable. Can you confirm @jonathanolson ?

**Comment by jonathanolson** [comment]
> It seemed like all the draggable pieces were "swipe to drag" pickupable.

For the game/lab screens it looks like everything in the play area is that way. Things in the panels, and mostly everything on the intro screen is NOT touch-to-snag.

> Can you take a pass through these sims and make recommendations for touch area sizes? 

That sounds good. I'm not sure how large I'd want to make the touch area on the buttons (if the user tries to interact with a group behind then it is more of a tradeoff).

**Comment by kathy-phet** [comment]
>For the game/lab screens it looks like everything in the play area is that way. Things in the panels, and mostly everything on the intro screen is NOT touch-to-snag.

Is there a reason not to do touch-to-snag everywhere. It always seems more seemless to me.

**Comment by kathy-phet** [comment]
>That sounds good. I'm not sure how large I'd want to make the touch area on the buttons (if the user tries to interact with a group behind then it is more of a tradeoff).
I think on these buttons that go away, you can make it pretty large precisely because it does go away if they click out. Once someone clicks out, or onto a different object, I assume they will no longer be active and wouldn't interfere with any other clicks.

**Comment by jonathanolson** [comment]
I made a quick first pass at touch areas for the sim:

![fractions-touch-3](https://user-images.githubusercontent.com/480878/49899427-ec2f6780-fe18-11e8-8f89-4578fd6d2d94.PNG)
![fractions-touch-4](https://user-images.githubusercontent.com/480878/49899428-ec2f6780-fe18-11e8-9071-4fcd213a91c3.PNG)
![fractions-touch-5](https://user-images.githubusercontent.com/480878/49899430-ecc7fe00-fe18-11e8-8d2d-ddb88fdd5ce7.PNG)
![fractions-touch-6](https://user-images.githubusercontent.com/480878/49899431-ecc7fe00-fe18-11e8-84c0-2e17082ffac5.PNG)
![fractions-touch-1](https://user-images.githubusercontent.com/480878/49899432-ecc7fe00-fe18-11e8-98bb-cf6174648009.PNG)
![fractions-touch-2](https://user-images.githubusercontent.com/480878/49899433-ecc7fe00-fe18-11e8-99a7-cfd243cfaae4.PNG)

**Comment by jonathanolson** [comment]
> Oh - I assume the "undo" button in the upper left also got some attention in the round?

Forgot to put pieces into containers to see that. I'll add an expansion to it.

**Comment by kathy-phet** [comment]
That looks good. I tried it on phettest. The ones I tried from the above collection seem to work well - a miss a few times, but not much.

Seems like the "undo" on the number version of the built fraction isn't done yet. 
I'm also wondering if you did the return button in the collection box? It seems like maybe yes, but I wasn't running it with the query parameter.

**Comment by jonathanolson** [comment]
Yup, also forgot about the number "return" button and the collection box "return" button. Those should be patched as well with the above commit.

**Comment by amanda-phet** [comment]
A visual look at the touch areas looks good to me, and when I'm on campus I can look at phettest on an iPad. 

(Funny, until I saw the touch areas, I didn't even know the number line was interactive! That seems like a good reason for the dot on the Fractions Equality numberline to be semi-transparent, since that one is *not* interactive.)

**Comment by amanda-phet** [comment]
Actually, can you expand the touch area for the accordion box? 
![image](https://user-images.githubusercontent.com/7852916/50018665-43eedf80-ff8d-11e8-85c1-1ebd578d97bb.png)

**Comment by jonathanolson** [comment]
Done:

![fractions-box-touch](https://user-images.githubusercontent.com/480878/50116130-866f2100-0206-11e9-8d2c-e36a87237ca3.PNG)

Anything else to do here?

**Comment by kathy-phet** [comment]
Just wondering if it is known why joist doesn't show the touch areas: 
![image](https://user-images.githubusercontent.com/5096804/50136288-8dbd1b80-0254-11e9-984e-4cde253a2a3f.png)

**Comment by jonathanolson** [comment]
> Just wondering if it is known why joist doesn't show the touch areas:

It looks like we're using a non-standard way of handling the mouse/touch areas in the code (NavigationBarScreenButton):

```js
    // add a transparent overlay for input handling and to size touchArea/mouseArea
    var overlay = new Rectangle( 0, 0, box.width, box.height, { center: box.center } );
```

Should we open an issue to handle that?

**Comment by kathy-phet** [comment]
I  leave it up to you and the other devs as to whether this is important to rework or if it has any implications for accessibility the way it is now.

**Comment by kathy-phet** [comment]
Perhaps I never his submit on my comment, but I also wanted to request to increase touch area around the Mixed Numbers check box.

**Comment by jonathanolson** [comment]
Increased the touch area around the Mixed Numbers checkbox, and created an issue for the navbar (https://github.com/phetsims/joist/issues/545).

Anything else to do here?

**Comment by amanda-phet** [comment]
Nope, thanks for making all these changes.
