### ISSUE TITLE
Home/navigation icons

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#30]
Let me know when we have navbar / homescreen icons and I can put them in.

**Comment by amanda-phet** [comment]
Thoughts on these icons? 

![image](https://user-images.githubusercontent.com/7852916/50178152-f80ba580-02c0-11e9-8fc7-568d1964bb26.png)

![image](https://user-images.githubusercontent.com/7852916/50178165-05289480-02c1-11e9-8cb9-d196420dec93.png)

![image](https://user-images.githubusercontent.com/7852916/50178187-107bc000-02c1-11e9-830b-562a9ed54c82.png)

![image](https://user-images.githubusercontent.com/7852916/50178206-1a052800-02c1-11e9-89f9-da44cfd45dc1.png)

For the Intro screens I would make a modified icon for the navbar with just one representation, but I think it's nice to see a medley on the homescreen icon.

**Comment by jonathanolson** [comment]
Those all look like they can be generated in code, so presumably I'd prefer to do it that way once the design is finalized unless I hear otherwise?

**Comment by kathy-phet** [comment]
Here are my suggestions ... take them or leave them. 

Fractions Intro = screen 2 look good. on screen 3 can you make them match (both be 3 quarters?)? the screen 1 icon - can we put the number fraction in there and remove the cup. also numberline should be less than 1 - that is the fractions should all match.
Can you include a proposal for the small icon too?

Fractions: Mixed Numbers = looks good to me

Fractions: Equality = looks good to me

Build a Fraction = looks good to me

**Comment by ariel-phet** [comment]
@amanda-phet I think everything looks good except "Intro" on Fractions: Intro and Fractions: Mixed Numbers. Both of those look a bit busy, and might not work well on the nav bar. I think as long as it looks different than the other screens, it doesn't have to perfectly represent all that is on the screen. Maybe just the number and the numberline?

**Comment by amanda-phet** [comment]
How about this- I reduced the number of fractions down to 2 for both intro screens and tweaked the representations slightly. I agree it has to look different than the other screens, but representing the differentiating content of each screen is important. 

Fractions: Intro
![image](https://user-images.githubusercontent.com/7852916/50233773-627c1e80-0371-11e9-8260-6ac669470bff.png)
![image](https://user-images.githubusercontent.com/7852916/50233790-6ad45980-0371-11e9-812e-0a7a67ca5654.png)

Fractions: Mixed Numbers
![image](https://user-images.githubusercontent.com/7852916/50233815-7c1d6600-0371-11e9-9ed6-735a7d419ece.png)
![image](https://user-images.githubusercontent.com/7852916/50233838-863f6480-0371-11e9-89ac-f166dab3caaa.png)

**Comment by amanda-phet** [comment]
@jonathanolson I think code is definitely the best way to generate these. Let me know if you need anything else from me.

**Comment by jonathanolson** [comment]
Updated master, how does it look now?

**Comment by amanda-phet** [comment]
I like that change. 

The only thing I am seeing: The Fraction Matcher game screen icon is being used in Fractions Equality, but the navbar icon looks really strange in Fractions Equality. I'm wondering if we need to specify an icon for this sim that is different from the Fraction Matcher sim. @jonathanolson can we do that? Perhaps just use the main home screen icon in the navbar. 
![image](https://user-images.githubusercontent.com/7852916/50660813-517d0100-0f5e-11e9-8ecd-b3717f0ad426.png)

![image](https://user-images.githubusercontent.com/7852916/50660824-5b066900-0f5e-11e9-8299-496f2ecb1d53.png)

**Comment by jonathanolson** [comment]
Implemented with the above (fractions-equality repo) commit. Can you see how it looks now?

**Comment by amanda-phet** [comment]
Looks good to me. Thanks!
