### ISSUE TITLE
stringTest=long component overlap

### ISSUE THREAD

**Issue by Denz1994** [phetsims/fractions-common#31]
Related to #29:

> Does the sim layout gracefully handle internationalized strings that are exceptionally long? (run with query parameter stringTest=long)

Here are some places to address.

Fractions-Intro: Intro Screen
![image](https://user-images.githubusercontent.com/13894380/50095473-a3462d00-01e3-11e9-9e4a-37eaeddea014.png)

Fractions-Intro: Game Screen
![image](https://user-images.githubusercontent.com/13894380/50095515-b6f19380-01e3-11e9-82ee-16afe879c9c6.png)

Fractions-Mixed-Numbers: Intro Screen
![image](https://user-images.githubusercontent.com/13894380/50095578-d983ac80-01e3-11e9-97fa-99c74dff602e.png)

Fractions-Mixed-Numbers: Intro Screen
![image](https://user-images.githubusercontent.com/13894380/50095624-f0c29a00-01e3-11e9-883c-9f4992335ce6.png)

Fractions-Mixed-Numbers: Game Screen
![image](https://user-images.githubusercontent.com/13894380/50095796-45661500-01e4-11e9-81c7-707ac71c493c.png)

Fractions-Mixed-Numbers: Game Screen (optional)
The next button width may be worth limiting despite not overlapping with any other component.
![image](https://user-images.githubusercontent.com/13894380/50095733-249dbf80-01e4-11e9-9feb-c6f32abf36b0.png)

**Comment by jonathanolson** [comment]
All of this should be fixed up now, can you verify?

**Comment by Denz1994** [comment]
Looking good. Closing.
