### ISSUE TITLE
Memory Leak testing

### ISSUE THREAD

**Issue by Denz1994** [phetsims/fractions-common#39]
Reported during #29.

> Does a heap comparison using Chrome Developer Tools indicate a memory leak?

Testing on macOS (10.13.6) + Chrome (71.0.3578.98) + incognito mode. Heap comparison shot in 15 minute intervals below.

Fractions intro:
![image](https://user-images.githubusercontent.com/13894380/50343275-3210bd80-04f4-11e9-9d55-502171545076.png)

**Comment by Denz1994** [comment]
Fractions - Equality
![image](https://user-images.githubusercontent.com/13894380/50343410-be22e500-04f4-11e9-8740-c736a0a39e10.png)

**Comment by Denz1994** [comment]
Build-A-Fraction:
]![image](https://user-images.githubusercontent.com/13894380/50343511-27a2f380-04f5-11e9-8c68-053d07578d7b.png)

**Comment by Denz1994** [comment]
Fractions-Mixed-Numbers:
![image](https://user-images.githubusercontent.com/13894380/50343536-473a1c00-04f5-11e9-843d-1f5a31089450.png)

**Comment by Denz1994** [comment]
Based on my experience doing previous memory test, I would have expected memory usage to  plateau after 2hrs. But results seem inconsistant especially in Fractions-Mixed-Numbers and Build-A-Fraction. 

There are some spikes in memory usage, and I believe those snapshots were taken when the sim was on a lab screen. I will do a long test at 30 min intervals and if the inconsitancy persist, commence memory leak testing on only the lab screens in the related sims.

**Comment by Denz1994** [comment]
Testing on macOS (10.13.6) + Chrome (71.0.3578.98) + incognito mode. Heap comparison shot in 30 minute intervals below.

Note: Snapshot 13 to Snapshot 14 was taken with about an hour interval.

**Comment by Denz1994** [comment]
Fractions Intro:
![image](https://user-images.githubusercontent.com/13894380/50615363-394fa800-0eb2-11e9-8afb-5e965a2ec392.png)

**Comment by Denz1994** [comment]
Fractions - Equality
![image](https://user-images.githubusercontent.com/13894380/50615401-6308cf00-0eb2-11e9-97ae-31e6a388eb02.png)

**Comment by Denz1994** [comment]
Build-A-Fraction:
![image](https://user-images.githubusercontent.com/13894380/50615530-f5a96e00-0eb2-11e9-8060-22aad0ffd597.png)

**Comment by jonathanolson** [comment]
Verified after 12 hours that there is no significant memory leak now. Closing.
