### ISSUE TITLE
Game screen performance

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/fractions-common#42]
When all 10 levels of a "game" are complete, the wipe transitions between levels are noticeably jumpy or just nonexistent. However, if only a couple are complete, you can still see the wipe. 

Found on Chrome, Mac OS. 

![untitled](https://user-images.githubusercontent.com/7852916/50456690-8c09ec80-0913-11e9-9ed1-58a76ead7252.gif)

Also: when checking FF, I don't see a wipe at all after completing just one level. Is this a FF bug?

**Comment by ariel-phet** [comment]
@jonathanolson and I discussed and he said:

> Presumably I could delay the animation start until the next frame, so that it starts right "after" the computation. So it would be a (hopefully) slight pause, followed by a smooth animation

We will try this strategy

**Comment by jonathanolson** [comment]
Implemented, see https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.16/phet/build-a-fraction_en_phet.html for how it feels.

**Comment by ariel-phet** [comment]
Looking good to me

**Comment by amanda-phet** [comment]
This seems to be much improved! Thanks!
