### ISSUE TITLE
Bring container/fraction to the front when pieces are dropped in?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#44]
Imagine you have two shapes overlapping like this on a lab screen:

![image](https://user-images.githubusercontent.com/5863899/50675191-a1cd8080-0fa9-11e9-8c6a-020ac2c8ee50.png)

I think it would be best that dropping a circle piece into the back one would bring the entire shape to the front. Currently it stays behind:

![image](https://user-images.githubusercontent.com/5863899/50675202-b90c6e00-0fa9-11e9-9565-f02c321522d7.png)

Just a thought. For phetsims/QA/issues/250.

**Comment by amanda-phet** [comment]
If it's not to difficult for @jonathanolson to fix, I think this would be fine to change. But the pieces can easily be rearranged at any time, so I am ok if this needs to be deferred.

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by KatieWoe** [comment]
This looks good.  I did notice that, when dragging the piece, sometimes any active buttons (the plus and minus, the left and right arrow, and the back arrow) will stay up and sometimes they disappear while dragging.  I can't seem to determine when this occurs and when it doesn't though.

**Comment by jonathanolson** [comment]
Hmm, I'm not seeing what I think you mean. Would you be able to record this behavior?

**Comment by KatieWoe** [comment]
@jonathanolson 
I think it stays if you've hit the plus/minus sign last, or the arrows, and may disappear otherwise.

![disappearingbuttons](https://user-images.githubusercontent.com/41024075/51138033-52831d80-17fd-11e9-8335-4738d6a4ac0e.gif)

**Comment by phet-steele** [comment]
> I think it stays if you've hit the plus/minus sign last, or the arrows, and may disappear otherwise.

That's what I see.

**Comment by jonathanolson** [comment]
This should be fixed with the above commit. Can you confirm?

**Comment by KatieWoe** [comment]
Behavior now seems more consistent on master.  When a piece is dragged from the tool bar the buttons disappear under both circumstances described above.  @jonathanolson

**Comment by jonathanolson** [comment]
Thanks! I believe that should be everything for this issue, closing.
