### ISSUE TITLE
Require all levels to be completed again to receive reward

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#45]
The games in FI, FMN, and BAF allow you to complete all levels to see the reward node, then refresh just ONE level, complete it and see the reward node again. This directly contradicts the efforts made in phetsims/expression-exchange/issues/85 (the sim with the pinnacle of PhET game design. You're welcome.) which requires that ALLLLLLLL levels are refreshed and completed again if one wants to see the reward node successive times.

Seen on Win 10 Chrome. For phetsims/QA/issues/250.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.17/phet/build-a-fraction_en_phet.html
Version: 1.0.0-dev.17 2019-01-04 01:10:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
</details>

**Comment by amanda-phet** [comment]
We are aware of this user interaction and decided we were not concerned about someone seeing the reward node again in this case.
