### ISSUE TITLE
Remove smiley and Next button when returning to a completed level

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#46]
The games in FMN, FI, and BAF have a small deviation from Expression Exchange's game (the sim with PhET's most clever game design). ExEx would not have a smiley face or Next button at all when returning to completed levels, yet the games in these fractions sims do. I'd have to imagine this was done in ExEx to motivate a player to refresh a level and keep playing.

Thoughts @ariel-phet? For phetsims/QA/issues/250.

**Comment by amanda-phet** [comment]
We weren't trying to exactly mimic Expression Exchange, so this discrepancy is not a concern. 

With that said, I would be fine if the smiley face and next button are not visible. @ariel-phet what do you think?

**Comment by phet-steele** [comment]
I realize I totally need to clarify that ExEx only hides the smiley and Next button on a completed level AFTER all levels have been completed.

**Comment by ariel-phet** [comment]
@jonathanolson if possible we should keep consistent with ExEx here. So it sounds like no "next" or "smiley face" will be shown after all levels are completed.

IMO this would refer to all Shape levels or all Number levels independently. So if you complete all shape levels the smiley and next would not appear (to encourage refreshing and further game) play, but the number levels (if all had not been completed for example) would still show these buttons as you completed levels.

**Comment by phet-steele** [comment]
Lookin' good.
