### ISSUE TITLE
Level 10 is missing the "Next" button

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#47]
See the flow of Expression Exchange's game (aka best PhET game ever) to see how this could be improved. Since we allow players to start at whatever level they like AND they must complete all levels to get a reward, we felt it was important to show the "Next" button on every level to encourage the completion of all levels. Pressing "Next" on level 10 (or level 8 in ExEx) would wrap around to level 1.

This concerns the game in FI, FMN, and BAF. For phetsims/QA/issues/250.

**Comment by amanda-phet** [comment]
I agree, level 10 should show the next button in this case, but I wouldn't want to show it all the time. If a (typical) user completes levels 1-10 in order, it wouldn't make sense to show the next button when they complete level 10 and get the reward node. 

@jonathanolson ideas for what to do? We are not trying to explicitly mimic the ExEx game, so without changing the entire game play, is there a way to show a next button on level 10 if all levels aren't complete?

**Comment by phet-steele** [comment]
> If a (typical) user completes levels 1-10 in order, it wouldn't make sense to show the next button when they complete level 10 and get the reward node.

In this scenario, they would never see the next button anyway since a) it would be covered by the reward dialog with the "Done" button, and b) moving forward with #46 means they would never see the Next button upon returning to a completed level 10 when all other levels have been completed.

**Comment by jonathanolson** [comment]
> is there a way to show a next button on level 10 if all levels aren't complete?

Yup, I can make that change. Sounds good to me.

**Comment by jonathanolson** [comment]
Implemented the concept of "go to the next uncompleted level, wrapping if necessary". If we really want the "Next" button to go to the next level instead (e.g. if you completed level 5, go to level 4 and complete it, should it go to 5, or skip to 6?) let me know.

Thoughts?

**Comment by amanda-phet** [comment]
@KatieWoe helped me confirm that clicking next on 10 takes you to 1 if it is not complete, but I don't think I like the next button taking you to "the next uncompleted level." You could in theory jump 9 levels, and that seems really strange to me. Happy to hear from others since I can't try it out at the moment, but when I play with dev.17 I don't mind that next might take me to a completed level. I can just keep clicking next, or go back to the level selection screen.

**Comment by phet-steele** [comment]
> I don't think I like the next button taking you to "the next uncompleted level."

👍

**Comment by jonathanolson** [comment]
Essentially reverted, but to where level 10 will wrap to level 1 (and every other case it will just go to the "next" level).

@phet-steele can you confirm?

**Comment by KatieWoe** [comment]
This seems to be working as described 1.0.0-rc.1
