### ISSUE TITLE
Remove undo buttons on a completed level

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#48]
The game in Expression Exchange (the superior PhET game) disables these undo buttons once all prompts have been answered, see https://github.com/phetsims/expression-exchange/issues/107. Too bad we didn’t write WHY we decided that, probably to motivate the player to refresh the level.

![image](https://user-images.githubusercontent.com/5863899/50670683-7ab38680-0f8a-11e9-8a79-c6d36b25472c.png)

Anyway, the games in FMN, FI, and BAF do not hide the undo buttons, as shown above. I'd advocate that they should! For phetsims/QA/issues/250.

**Comment by amanda-phet** [comment]
We decided to leave these buttons in the Fractions suite games. We didn't record *why* either, but I know it was discussed!
