### ISSUE TITLE
Animate incorrect answers just to the left of the collection area

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#49]
Out of curiosity, why do the games in FI, FMN, and BAF bounce the term for an incorrect answer to the middle of the play area? Expression Exchange's game (with superhuman game design) just bounces the term to the left of the collection area they were attempting to place the answer in, instead of traveling all the way to the middle of the screen. This isn't a big deal either way, but it does allow for the player to make another attempt a few seconds faster since they wouldn't have to wait for the term to animate as far.

For phetsims/QA/issues/250.

**Comment by amanda-phet** [comment]
In ExEx there could be loose pieces in the middle of the screen, but that is not possible in Fractions games. Pieces can only be in containers. Since users are building in those containers, it makes more sense to have the container in the central play area where you can easily drag pieces up.
