### ISSUE TITLE
Sequential fill order for game shapes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#5]
I tuned the rotations and fill order of the game shapes (when sequentially filled) so that it matches the general decisions for the rest of the sim:

![fill-order](https://user-images.githubusercontent.com/480878/47142917-3fee5c00-d281-11e8-8d1a-c2f1eafd5e67.png)

They start filling on the "red" and end at the "cyan" (indicating the order). Let me know if any need to be tweaked (notably the order, main rotation, etc.)

Furthermore, that is the "main" set of shapes. There are also notably some "grid shapes" for some of the larger "arbitrary number" ones, since the original sim seems to keep a square aspect ratio:

![fill-order-3](https://user-images.githubusercontent.com/480878/47143195-d753af00-d281-11e8-914f-e2bc161fa39d.png)

And there is a certain subset of shapes that may be used for some levels ("game shapes"):

![fill-order-2](https://user-images.githubusercontent.com/480878/47143222-e5093480-d281-11e8-9de3-7fbefce32d28.png)

And also some sets of shapes used when we need to represent multiple denominators of anything (6 or lower) with the same general shape ("universal" ones):

![fill-order-4](https://user-images.githubusercontent.com/480878/47143301-0ec25b80-d282-11e8-932b-f8987823bba3.png)

It would be great to know your opinion on which shapes should be used in the following cases:

- Where the design doc says "all representations possible" (unclear if we want the "game" shapes or the "main" shapes (includes some like the tetris/L/etc.)
- Places where the same general representation will need to support denominators from 1 to 6 (the universal forms above are used)
- Places where the same general representation will need to support denominators from 1 to 12 (the grid forms are used now) IN THE SAME TARGET, e.g. mixed numbers levels 9 and 10.

**Comment by jonathanolson** [comment]
Also if relevant, the code exists to generate the "flowers" with different sizes, e.g.:

![fill-order-5](https://user-images.githubusercontent.com/480878/47143918-7fb64300-d283-11e8-96cd-0bdca2fde0b5.png)

if those would work better than any existing shapes.

**Comment by ariel-phet** [comment]
@jonathanolson @amanda-phet I think the fill order looks good.

As for the other questions, my main litmus test would be if the shape is reasonable to count for the given denominator. For instance, the single row or column square gets hard to count with large denominators, but the grid shape works well for large denominators.

**Comment by amanda-phet** [comment]
The only one that looks slightly odd to me is the triangle, but I just confirmed that it matches the behavior in the java sim so I think this all looks good! 

>* Where the design doc says "all representations possible" (unclear if we want the "game" shapes or the "main" shapes (includes some like the tetris/L/etc.)

I will have to review the design doc, but I think this means game and main shapes. 

>* Places where the same general representation will need to support denominators from 1 to 6 (the universal forms above are used)

I'm not sure I follow this question, but it seems any applicable shapes could be used? 

>* Places where the same general representation will need to support denominators from 1 to 12 (the grid forms are used now) IN THE SAME TARGET, e.g. mixed numbers levels 9 and 10.

Are we talking about the levels like this? 
![image](https://user-images.githubusercontent.com/7852916/47515957-642dd800-d841-11e8-9e3f-beb97fc57616.png)
If so, it seems like right now circles and rectangles are being used. I think we should continue using those shapes because it gets tricky to pick up pieces any smaller.

**Comment by jonathanolson** [comment]
I'm mainly discussing the collection-box targets for "number" levels, e.g.:

<img width="972" alt="screen shot 2018-10-25 at 5 09 41 pm" src="https://user-images.githubusercontent.com/480878/47535425-d077fe00-d878-11e8-9e49-e6389e76c929.png">

Maybe this would benefit from a brief call sometime to discuss?

**Comment by jonathanolson** [comment]
IIRC, the main decision was "leave it as-is, except for the asymmetric grids in mixed levels 9/10". I've replaced that so that it is just pies/bars.

Feel free to reopen if any changes are desired.
