### ISSUE TITLE
Incorrect answer has no audible feedback

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#50]
We have no “boing” sound for an incorrect answer in FI, FMN, and BAF games. Play the game in Expression Exchange (the greatest gaming achievement in PhET's history) to see my preferred behaviour.

Seen on Win 10 Chrome. For phetsims/QA/issues/250.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.17/phet/build-a-fraction_en_phet.html
Version: 1.0.0-dev.17 2019-01-04 01:10:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
</details>

**Comment by amanda-phet** [comment]
I think it's pretty clear that an answer is incorrect when the piece bounces out, but am open to having an incorrect sound if other team members want it. 

@ariel-phet and @kathy-phet let me know if you want an incorrect boing.

**Comment by ariel-phet** [comment]
I am all for consistency. Considering ExEx is our first HTML5 "build" style game where you are building to targets, I think it would be reasonable to include this sound on bounce out.

@jonathanolson see Expression Exchange for the "boing" sound

**Comment by jonathanolson** [comment]
Implemented in master (also following ExEx behavior that if a collection area is full, dragging something over it will NOT give the incorrect answer noise).

**Comment by ariel-phet** [comment]
All looking (sounding) good. Closing
