### ISSUE TITLE
Button sizes are all over the place!

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#51]
The button sizes (Reset All, Sound, Timer) on the game screens of Fractions: Equality and Fraction Matcher are much bigger than their counterparts in the other fractions sims. Particularly within Fractions: Equality, both screens have different sized Reset All buttons:

![image](https://user-images.githubusercontent.com/5863899/50677135-56b96a80-0fb5-11e9-9754-f083fd21308d.png)
![image](https://user-images.githubusercontent.com/5863899/50677138-62a52c80-0fb5-11e9-9c8d-941746c922d5.png)

PhET logo is the same size in both of those screenshots. For phetsims/QA/issues/251.

**Comment by amanda-phet** [comment]
@jonathanolson did the defaults change for reset-all and other buttons in the last 4 years? If so, perhaps we should update the buttons in Fraction Matcher to match the latest buttons.

**Comment by jonathanolson** [comment]
> @jonathanolson did the defaults change for reset-all and other buttons in the last 4 years? If so, perhaps we should update the buttons in Fraction Matcher to match the latest buttons.

It looks like fraction-matcher code is using non-standard layout bounds. This ideally would be converted to the default, or at least the correct aspect ratio (see https://github.com/phetsims/joist/issues/542).

@ariel-phet should this be updated now, or left for when more matcher work is done?

**Comment by ariel-phet** [comment]
@jonathanolson left for when fraction matcher work is done. Marking deferred.

**Comment by jonathanolson** [comment]
The sizes should now be consistent, since fraction-matcher/etc. is now using the standard layout bounds. Can you verify?

**Comment by phet-steele** [comment]
@jonathanolson the sizes are now correct, but fraction-equality has the Reset All button in two different places between its screens.

**Comment by jonathanolson** [comment]
@ariel-phet mind if I tweak the spacing for the matching screens to match the others (as far as the reset-all is concerned)?

**Comment by ariel-phet** [comment]
@jonathanolson feel free to tweak spacing so it matches

**Comment by jonathanolson** [comment]
@phet-steele this should be handled in master. Can you verify?

**Comment by KatieWoe** [comment]
Fraction comparison is much larger, but I don't know if it counts.  All the others seem appropriately sized on master.

**Comment by jonathanolson** [comment]
Fraction Comparison doesn't use the fractions-common code (and I'm unfamiliar with it). @ariel-phet should I look into patching button sizes on that sim?

**Comment by ariel-phet** [comment]
@jonathanolson no... the fraction comparisons sim is from long ago, and not schedule to be worked on any time in the near future. If we do eventually work on it, we will move it to the fractions-common code.

The button size look good, however, on Fractions: Intro, the reset all button jumps around in placement between screens a bit, and it is "floating" on the Lab screen

Can you make the position fixed and match all three screens of the Fractions: Intro sim have the same position of reset all button as the first screen? (So when I flip screens, it does not move).

**Comment by jonathanolson** [comment]
For the layout of the reset-all button:

1. The Lab screen uses dynamic layout, so it's tricky to adjust its position if the sim is width-limited. If it's height-limited, it should be possible to have it be in the "same" position. But for the example below, do you want the reset-all button to be floating above the bottom panel?

![area-dynamic](https://user-images.githubusercontent.com/480878/58597136-e5b07300-8233-11e9-9b80-526cf2927693.PNG)

2. The game screen vertically centered the sound button, reset-all button AND page-selection buttons. Should these all be bottom-aligned (so the reset-all button would go down slightly to match, and the page-selection buttons in the center would go down further)?

**Comment by jonathanolson** [comment]
I'll change alignments on the 2nd screen, and have the reset-all button not float right when vertically constrained on the 3rd screen.

**Comment by jonathanolson** [comment]
Done above. @ariel-phet can you see how this looks?

**Comment by ariel-phet** [comment]
Looking good, closing
