### ISSUE TITLE
Change sim title to "Fractions: Intro"?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#52]
Shouldn't the title of Fractions Intro instead have a colon like “Fractions: Intro”? This would match the other sims like Fractions: Equality and Fractions: Mixed Numbers. Not to call out @jonathanolson, but it looks like he subconsciously added a colon in the title of phetsims/QA/issues/252 😄.

**Comment by amanda-phet** [comment]
Yes the title is supposed to have a colon.

**Comment by jonathanolson** [comment]
Done with the above commit.
