### ISSUE TITLE
Level select titles are missing and verbose (sometimes)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fractions-common#53]
The level select screens in FI, FMN, and BAF do not have a title, unlike FE and FM:

![image](https://user-images.githubusercontent.com/5863899/50670639-2c9e8300-0f8a-11e9-8ed8-7164a98fe3ee.png)

Furthermore, the only reason the title “Fractions: Choose your level!” is used in the FM level select is because “Fractions” is the name of the screen. The other screen in that sim is named “Mixed Numbers” and therefore the title says “Mixed Numbers: Choose your level!”. All that being said, the game screen in FE (above screenshot) still says “Fractions: Choose your level!” while the word “Fractions” in the title doesn’t make sense to belong there. The name of the screen in FE is simply “Game” and only has that one type of game.

So I'd propose stripping "Fractions: " from the title of the level select in FE, then adding "Choose your level!" as a title in FI, FMN, and BAF. All of this in the name of consistency. @ariel-phet?

For phetsims/QA/issues/250.

**Comment by amanda-phet** [comment]
>So I'd propose stripping "Fractions: " from the title of the level select in FE, the adding "Choose your level!" as a title in FI, FMN, and BAF. All of this in the name of consistency.

That's my vote as well. FM still needs those titles, but if we can make that change in FE I think that would be best.

**Comment by jonathanolson** [comment]
So to be clear, this would leave fraction-matcher in the same state as it is now, but when the matcher screen is in fractions-equality it would only have "Choose your level!" (instead of the current behavior)?

Also if we're adding this to the newer game screens, I assume you don't want the text sliding left/right when the level icons do?

**Comment by ariel-phet** [comment]
@jonathanolson yes you are correct when you say:

> leave fraction-matcher in the same state as it is now, but when the matcher screen is in fractions-equality it would only have "Choose your level!"

In addition, I agree, we do not need the text sliding left/right when the level icons slide.

**Comment by amanda-phet** [comment]
>So to be clear, this would leave fraction-matcher in the same state as it is now, but when the matcher screen is in fractions-equality it would only have "Choose your level!" (instead of the current behavior)?

Yes, that is correct.

**Comment by jonathanolson** [comment]
Should be implemented, does this look good?

**Comment by phet-steele** [comment]
This looks fine to me @jonathanolson. But now that I see it, maybe fraction-matcher could just say "Choose Your Level!" without the prefix as well.

**Comment by phet-steele** [comment]
@amanda-phet different sims have different fonts for this title, just FYI in case you care.

**Comment by ariel-phet** [comment]
@jonathanolson @phet-steele I don't think we want to touch Fraction Matcher for the moment. 

@phet-steele feel free to make a separate "polish" issue regarding fonts. Might wait until after 1.0, but good to note. 

Closing
