### ISSUE TITLE
Image for level select seem backwards

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#56]
For https://github.com/phetsims/QA/issues/250, https://github.com/phetsims/QA/issues/252, and https://github.com/phetsims/QA/issues/253
The images shown when selecting a level show either number fractions, or shapes split in to pieces.  The images show the thing you will be trying to match.  I think it would make more sense if they showed what you would be building.  For example, if you click on an image with a circle, you will be building a fraction out of numbers to match a given shape.  I think it would make more sense if clicking on the circle led you to a level where you built a shape to match a number.  Not a strong feeling, but it did lead to some confusion as I played, so may be worth considering.

**Comment by amanda-phet** [comment]
That's interesting you bring this up because this was a change that happened between dev.10 and dev.11. 

@ariel-phet should we interview on this since it is a change from the java version?

**Comment by ariel-phet** [comment]
@KatieWoe we had some debate about this...I actually found the reverse confusing so we changed it.

One big reason for me is that many of the "shapes" we show never appear as things you can build with (since we only ever build with circle and rectangle slices).

I think the game level icons are clearer this way, which is why I opted for the change. 

@phet-steele any thoughts?

**Comment by amanda-phet** [comment]
@arouinfar showed the sim to a kid today in an interview and might have some insight either way. I haven't reviewed the footage yet myself.

**Comment by arouinfar** [comment]
The two students I interviewed used Fractions: Mixed Numbers dev.10. They did not spend any meaningful amount of time on the level selection screen, so I cannot speak to how students interpret the icons. They both started with the Level 1 in the top row (building shapes to match the given mixed numbers). After finishing a level, they would click the "Next" button to move onto the next level. 

Personally, I think the icons in dev.10 are clearer. The icons correspond to what the student will build -- shapes or mixed numbers. While it's true that the shape icons aren't representative of the exact things a student will build, the same can be said of the mixed number icons. The mixed numbers are always less than 4 and the smallest fraction is 1/8 (I think), but mixed number icons follow the pattern of n 1/n, where n is the level number. 

I think the shape icons are more visually interesting. If the goal is for students to first play the challenges where they build shapes, then it would make sense for those icons to be the most attractive.

**Comment by phet-steele** [comment]
> @phet-steele any thoughts?

I have a few thoughts about things in life, but I'm assuming you want my thoughts about this issue? 😛 

I'd be in favor of switching this back to shapes on top, numbers on bottom.

When I look at the level select, the icons are asking me, "Do you want to practice with shapes?" or "Do you want to practice with numbers?" So I'd assume the version I choose would see me practicing with the icon I see.

Now what I mean by "practice" is the crux of this, and to me it refers to what I would be manipulating and building. The targets on the right are already answers, so the visual representation and any math involved are already worked out for me. The gameplay involves me working towards a different interpretation, from scratch, with the tools along the bottom. In other words, the challenge is using the pieces along the bottom, ergo the challenge is what is used as the icon.

**Comment by ariel-phet** [comment]
Appears I have been outvoted, which is fine with me.

@jonathanolson please revert icons back to dev.10 style. This keeps the design the same as with the original sim.

**Comment by jonathanolson** [comment]
Done in master.

**Comment by ariel-phet** [comment]
Looks good closing
