### ISSUE TITLE
Hitting back arrow may take you to previous game screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#58]
For https://github.com/phetsims/QA/issues/250, https://github.com/phetsims/QA/issues/252, and https://github.com/phetsims/QA/issues/253
May no longer be an issue depending on the outcome of https://github.com/phetsims/fractions-common/issues/54.  When you hit the back arrow in a game, it takes you to the last level select screen you saw.  This is not necessarily the one that has the level you were just playing.  It may make more sense to put the player on the level select screen that has their most recent level instead.
To reproduce:
1. Go to a game with two level select screens
2. Choose a level five (the last level before the next screen)
3. Beat the level and hit next under the smile face
4. Hit the back arrow

![change screens](https://user-images.githubusercontent.com/41024075/50701014-77abab00-1009-11e9-8f46-e2fd92d1e922.gif)

**Comment by amanda-phet** [comment]
This seems like a logical idea. 

@jonathanolson can this be done easily?

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by KatieWoe** [comment]
Confirmed @jonathanolson

**Comment by jonathanolson** [comment]
Thanks!
