### ISSUE TITLE
Inconsistent behavior of container when dragged with touch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#59]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/250, https://github.com/phetsims/QA/issues/252, and https://github.com/phetsims/QA/issues/253
When dragging a shape container from a bin using a mouse the bin becomes the focus and it gains the plus sign and arrows.  When the shape container is dragged using the touch screen it does not gain that focus and does not gain the plus and arrow signs.  Anything that had focus before will lose it and you can focus on the new container by dropping it in the play area and tapping it.  So this does not interfere with play, but is an inconsistency.
**Steps to reproduce:**
1. Go to the Lab screen
2. Use a mouse to drag out a circle container
3. Use the touch screen to drag out another circle container

**Screenshots:**
![differentwithtouch](https://user-images.githubusercontent.com/41024075/50702608-a415f600-100e-11e9-95de-d9f0eafb52d6.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Build a Fraction‬
URL: https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.17/phet/build-a-fraction_en_phet.html
Version: 1.0.0-dev.17 2019-01-04 01:10:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
Is this a multitouch bug? seems like just a bug to me. 

I agree this should be fixed though.

**Comment by KatieWoe** [comment]
More like single touch.  I may have misinterpreted multitouch term

**Comment by jonathanolson** [comment]
Behavior should be consistent now.

Can you check that mouse/touch handling is working here as expected? I also made a patch for the Lab screen so that the right group is selected when you go into the screen (the home-screen click to go to the Lab screen itself was deselecting the group, and the buttons disappeared).

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by jonathanolson** [comment]
Thanks!
