### ISSUE TITLE
Only the first Mixed number displays the "no" sign

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#61]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/250 and https://github.com/phetsims/QA/issues/253
The Mixed Number fractions that allow you to drag numbers will not allow a 1 on the bottom fraction.  This is signaled by "no" sign.  When in a game that uses these tools, only the one that is initially out will display this behavior.  Any that appear after the first, whether dragged out by the player or pulled out after a correct answer, will not display the "no" sign.  If the original is put in the tool box and removed again it still behaves correctly.  A 1 cannot be put in that spot, even if the "no" sign fails to appear.  This issue is not present in the lab screens.
**Steps to reproduce:**
1. Go to any game level where you build mixed number fractions
2. Drag a 1 out and note the "no" sign
3. Put the 1 back
4. Drag out a second mixed number frame
5. Drag the 1 out again and note the behavior

**Screenshots:**
![inconsistantno](https://user-images.githubusercontent.com/41024075/50708759-bb5ede80-1022-11e9-81d9-4523574cb9cf.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Build a Fraction‬
URL: https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.17/phet/build-a-fraction_en_phet.html
Version: 1.0.0-dev.17 2019-01-04 01:10:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
Looks like a bug to me too. Good catch.

**Comment by KatieWoe** [comment]
Can also occur in the numerator if trying to put a larger number than the denominator there.  Mixed number only

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by KatieWoe** [comment]
Looks good @jonathanolson

**Comment by jonathanolson** [comment]
Thanks!
