### ISSUE TITLE
No touch screen on undo arrow

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#62]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/252, https://github.com/phetsims/QA/issues/253, and https://github.com/phetsims/QA/issues/250
The undo arrow for the number fractions does not respond to the touch screen
**Steps to reproduce:**
1. Go to the lab or game screen and make sure a number fraction builder is available (mixed or not)
2. Fill in the fraction with random numbers
3. Try to use touch to hit the undo button

**Screenshots:**
https://drive.google.com/file/d/17fSPUaulzmzpnHh9JOgHnBGsDQLQtbp4/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Fractions Intro‬
URL: https://phet-dev.colorado.edu/html/fractions-intro/1.0.0-dev.17/phet/fractions-intro_en_phet.html
Version: 1.0.0-dev.17 2019-01-04 01:13:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Just checked iPad.  This issue makes using the undo button in these situations impossible on iPad

**Comment by jonathanolson** [comment]
I have a temporary solution above.

@samreid it ended up that aborting the enter/exit events led to incorrect pointer counting in other components, so that seems like an infeasible solution.

Additionally, since those events DON'T include the full trail when they are fired on ancestors, it was difficult to check.

Temporary workaround reaches into the button to check what pointers are "over" it, and something like that might be a good longer-term solution (it's grabbing private content right now, yikes).

Would you have time to discuss again?

**Comment by samreid** [comment]
> @samreid it ended up that aborting the enter/exit events led to incorrect pointer counting in other components, so that seems like an infeasible solution.

Why did aborting exit/enter events lead to incorrect pointer counting elsewhere?

> Temporary workaround reaches into the button to check what pointers are "over" it, and something like that might be a good longer-term solution (it's grabbing private content right now, yikes).

I see the proposed solution in GroupNode.  Not sure how it might be generalized to other component types in the general case where a client doesn't know if it will have a button child or not (or how to access it).  

I messaged you on Slack about scheduling further discussion.

**Comment by jonathanolson** [comment]
The discussed permanent solution committed above (along with handling a few complications that came up). @KatieWoe can you verify this behavior on master?

**Comment by KatieWoe** [comment]
@jonathanolson confirmed

**Comment by jonathanolson** [comment]
Thanks!
