### ISSUE TITLE
Green pie chunk stops rotating

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#64]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/251, https://github.com/phetsims/QA/issues/252, https://github.com/phetsims/QA/issues/253
On the first screens of the three sims above, you can drag pieces of the green pie charts towards those graphs.  As you do this the pieces rotate to line up with the orientation they will be dropped in to.  If the piece is dragged out of a certain area that rotation stops, no matter where that rotation was.  This is most easily seen with the 1/2 piece.
**Steps to reproduce:**
1. Go to one of the intro screens with the green pie charts
2. Set the piece sizes to 1/2
3. Drag a piece out.  Note where the orientation changes happen
4. As one of the changes occurs, quickly drag the piece to the top of the screen to the type selection bar

**Screenshots:**
![frozenturn](https://user-images.githubusercontent.com/41024075/50788167-d7a68980-1275-11e9-9352-257924c68989.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fractions: Equality‬
URL: https://phet-dev.colorado.edu/html/fractions-equality/1.0.0-dev.7/phet/fractions-equality_en_phet.html
Version: 1.0.0-dev.7 2019-01-04 01:12:43 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by ariel-phet** [comment]
@KatieWoe thanks for pointing out...however, I do not think this behavior needs to be changed. 

Closing
