### ISSUE TITLE
No reward for beating 10 levels iOS

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#65]
Device
iPad (2018)
OS
iOS 12
Browser
Safari
For https://github.com/phetsims/QA/issues/253.  Need to check other sims.
Upon beating Level 10 (and all others before) in Fractions Mixed Numbers (building shapes to match fractions) the sound played and the dialog popped up, but no confetti dropped.  Was in portrait mode at the time.
Edit: Same for other type of game in Fractions Mixed Numbers
Edit 2: Occurs in Landscape as well

**Comment by KatieWoe** [comment]
Also in https://github.com/phetsims/QA/issues/252 and https://github.com/phetsims/QA/issues/250
Does not occur when a level is beaten in Fractions: Equality

**Comment by ariel-phet** [comment]
@jonathanolson - this would certainly be good to fix, but I do not see it as essential for publishing 1.0

Marking `priority:4-low`

**Comment by jonathanolson** [comment]
I was under the impression that this was a desired feature, since the performance of the RewardNode was low. There is code explicitly preventing the RewardNode from showing up on mobile safari.

Should I remove that condition? (It's easy to do)

**Comment by KatieWoe** [comment]
I wasn't aware that this was intended.  It doesn't bother me, so if this improves performance I don't see a problem.

**Comment by ariel-phet** [comment]
@KatieWoe @jonathanolson forgot this was intentional. Closing.
