### ISSUE TITLE
View Time Records in game for Fractions: Equality

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#66]
I noticed that there doesn't seem to be any record of the time you got on different levels you've already beaten when playing the game in fractions: equality.  This seems a bit odd to me since I think this was possible in other games.  Not necessary, but I thought it might be a good feature to bring up.
For https://github.com/phetsims/QA/issues/251

**Comment by ariel-phet** [comment]
I believe we had time recorded in a early version of fraction matcher, I will see if I can trace down the published version that had it.

**Comment by ariel-phet** [comment]
@KatieWoe do you mean a time recorded on the level selection screen? 

@jonathanolson I believe there is a "best time" option in Vegas that will display best times on the level selection icons. But perhaps that is best to included when we revisit the Fraction Matcher code? Let me know.

**Comment by KatieWoe** [comment]
@ariel-phet yes that is what I mean.

**Comment by jonathanolson** [comment]
> But perhaps that is best to included when we revisit the Fraction Matcher code? Let me know.

Probably best, yes.

**Comment by ariel-phet** [comment]
OK, marking deferred

**Comment by jonathanolson** [comment]
I believe this was implemented:

<img width="1074" alt="Screen Shot 2019-06-07 at 11 41 51 AM" src="https://user-images.githubusercontent.com/480878/59122943-48cb9500-8919-11e9-8aeb-63e4504e49dc.png">

@KatieWoe is there anything else to do for this issue?

**Comment by KatieWoe** [comment]
I don't believe anything else had to be done.  I'll look for any bugs when it comes up for rc.

**Comment by KatieWoe** [comment]
Things look ok.  I noticed that the time record disappears if you make a mistake, and will come back if you complete again perfectly with the correct record whether or not you set it that time or its the old record.  I think that is fine.

**Comment by jonathanolson** [comment]
> I noticed that the time record disappears if you make a mistake, and will come back if you complete again perfectly with the correct record whether or not you set it that time or its the old record. I think that is fine.

I believe that was the desired behavior, so I'm going to close the issue. Thanks!
