### ISSUE TITLE
Images in correct bins off center

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#67]
**Device**
Chadwick (chromebook)
**OS**
ChromeOS
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/252
Some of the pie shapes are off center in their answer bins.  I will update this issue if I find it in the other sims/with the fractions
**Steps to reproduce**
1. Go to the level and build all the necessary shapes
2. Put them in the answer bins (Don't have to be done all at once)
3. Repeat if this does not occur

**Screenshot**
![pastedimage](https://user-images.githubusercontent.com/41024075/50800463-932ee400-129d-11e9-950d-99b70dadf946.png)

**Comment by KatieWoe** [comment]
Update on conditions: Occurred on Win 10 chrome and firefox.  Only seems to occur with the circular shapes, and not rectangular.  Not restricted by level.  Occurs in https://github.com/phetsims/QA/issues/253 and https://github.com/phetsims/QA/issues/250.  Have not seen with fractions or the square pieces.  Dropping the circle off center may help this issue appear.

**Comment by ariel-phet** [comment]
@jonathanolson would be nice to fix.

**Comment by jonathanolson** [comment]
Should be fixed in master, can you verify?

**Comment by KatieWoe** [comment]
Did a couple of levels and didn't see any problems

**Comment by jonathanolson** [comment]
Closing, thanks!
