### ISSUE TITLE
Long Strings in Equality game overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#68]
When stringTest=long and playing the game, different strings are allowed to overlap.  For https://github.com/phetsims/QA/issues/251
Steps:
1. Turn on the timer to see all strings
2. Select any level

![overlaps](https://user-images.githubusercontent.com/41024075/50840521-efd2e300-131f-11e9-9816-d61722f771e5.PNG)

**Comment by jonathanolson** [comment]
Should be handled by the above commit.

**Comment by KatieWoe** [comment]
Looks good

**Comment by KatieWoe** [comment]
Looks good 1.0.0-rc.1
