### ISSUE TITLE
Visual distortion/"ghosting" on fractions in Safari

### ISSUE THREAD

**Issue by rea-laura** [phetsims/fractions-common#70]
<b>Test Device</b>

Jordan

<b>Operating System</b>

MacOS 10.14.2

<b>Browser</b>

Safari (not found on any other browsers)

<b>Problem description</b>

For https://github.com/phetsims/QA/issues/250:

small visual distortion when fractions are moved in a certain way.

<b>Steps to Reproduce</b>

1) open sim
2) go to "build a fraction"
3) open any level with a shape icon
4) place a number in the numerator
5) slowly drag another number across the denominator borders. If no distortion appears, move the entire fraction to another location on the screen and try again.

<b>Visuals</b>

Note that the circle around the cursor is from the screen capture software, and does not actually appear in the simulation.

![kapture 2019-01-08 at 10 38 02](https://user-images.githubusercontent.com/44005544/50849014-0cc4e180-1333-11e9-8b65-b27d80e707df.gif)

**Comment by ariel-phet** [comment]
@jonathanolson looks like a browser bug to me, and not something I feel needs to be addressed currently. If there is a relevant scenery issue, perhaps tag this issue withing that scenery issue and close this one.

**Comment by KatieWoe** [comment]
I tried to replicate this for a bit on 10.13 and was unable to

**Comment by jonathanolson** [comment]
Doesn't match the behavior of other issues I've experienced before, so I opened https://github.com/phetsims/scenery/issues/923 for this. Closing.
