### ISSUE TITLE
Equality Game time continues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#73]
For https://github.com/phetsims/QA/issues/260
Something a bit odd I noticed.  Once the game is complete the dialog with your time (and record if it is different) comes up.  However, the timer continues to count up and is still visible.  Minor issue, but I wanted to mention it here.
https://drive.google.com/file/d/113Bnux_u7QSY4jzH8p83Tlhvnew3gyCR/view?usp=sharing

**Comment by ariel-phet** [comment]
Deferring until we work on Fraction Matcher (after 1.0 of all these sims are published).

However, does seem worth fixing when we get to Fraction Matcher.

**Comment by KatieWoe** [comment]
Happens in https://github.com/phetsims/QA/issues/294

**Comment by jonathanolson** [comment]
I believe this was fixed recently. @KatieWoe can you confirm that this does not happen in master?

**Comment by KatieWoe** [comment]
It does seem fixed in master

**Comment by KatieWoe** [comment]
Looks good 1.1.0-rc.2

**Comment by jonathanolson** [comment]
Thanks! Closing.
