### ISSUE TITLE
Equality stringTest=long victory dialog and number bar

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#75]
For https://github.com/phetsims/QA/issues/260
When stringTest=long, the victory dialog can be wider than the window.  You will likely need to resize the window to see this occur.  It is also visible on the iPad as seen below.  In addition, while the long strings no longer overlap, when the number line to compare to objects appears, it cuts in to part of one of the strings.
![cutoff](https://user-images.githubusercontent.com/41024075/51403611-32f63880-1b0e-11e9-8383-32ddda9af3c3.jpg)
![99cf7b75-d0bc-4a74-9df7-cd9b0bda0675](https://user-images.githubusercontent.com/41024075/51403628-3d183700-1b0e-11e9-9be7-469d393ea4d4.png)
![a4945494-7164-4c61-b61f-0f0381419e23](https://user-images.githubusercontent.com/41024075/51403629-3d183700-1b0e-11e9-978b-28a83acc3aab.png)

**Comment by ariel-phet** [comment]
@jonathanolson the fraction matcher ones can wait, if the reward node dialog is easy to fix go ahead. If anything but a quick fix, please defer until after 1.0.

**Comment by jonathanolson** [comment]
The "My Matches" and level complete node maxWidths were adjusted (master and on RC branches).

@KatieWoe can you check the behavior on master?

**Comment by KatieWoe** [comment]
1.0.0-rc.2 looks good
