### ISSUE TITLE
Odd show answer vs try again behavior in equality game

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#77]
For https://github.com/phetsims/QA/issues/260
Conversation from slack:
>Kathryn Woessner [9:16 AM]
>Looking at the equality game, and I had a few questions about how it determines when to say try again, and when it says show answer.  At first I thought it said show answer if one of the pieces had already been used in a wrong answer, but I've found a way to make the same piece be part of up to 5 wrong answers.  Is this a bug, or am I misunderstanding how it decides?

>Jonathan Olson [10:32 AM]
>I really have no idea how the 2nd tab on fractions-equality works. I'll be heavily reworking/improving the code soon. I'd need to check the design doc to see, but it is probably worth creating issues for anything that seems "off" on that tab

Instructions:
1. Go to an easy level of the game and select a piece to be the one to receive the numerous wrong answers.  This is piece "A"
2. Put "A" and a wrong piece as the first answer
3. Select try again and remove "A"
4. Answer correctly with the remaining piece
5. Put "A" with a different wrong piece and repeat up to 5 times

**Comment by ariel-phet** [comment]
@KatieWoe this is the correct behavior

Basically, once you have put something up on the "pads" on each side and press check, you have used your first "try". You get 2 points for right on the first try, 1 point for correct on the second try. After the second try scoring is reset.

Basically, the "normal" flow is going to be, try a match. Realize something is amiss if wrong, and replace one of the pieces.
