### ISSUE TITLE
Can't drag empty fractions by line

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#79]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/261, https://github.com/phetsims/QA/issues/262, and https://github.com/phetsims/QA/issues/259
It is not possible to drag the number fraction builders by their line, either with mouse or touch.  Anywhere else within the pointer area will work.  Likely a minor issue.
**Steps to reproduce:**
1. Go to either the lab screen or a game level in which you build a number fraction
2. Try to drag either type of the number fraction builder by the fraction line
3. Try to drag either type of the number fraction builder by any other part

**Screenshots:**
![cantdragmiddleline](https://user-images.githubusercontent.com/41024075/51414348-5c738c00-1b2f-11e9-8795-e66746c8c72b.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fractions: Intro‬
URL: https://phet-dev.colorado.edu/html/fractions-intro/1.0.0-rc.1/phet/fractions-intro_en_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2019-01-16 21:29:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by ariel-phet** [comment]
@jonathanolson seems worthy of fixing for a better UX if easy to do.

**Comment by jonathanolson** [comment]
Patched in master and on the release branches. @KatieWoe can you verify? (Everywhere in the mouse/touch area should now work to drag it, the gaps between rectangles were also problematic before)

-Jonathan Olson

**Comment by KatieWoe** [comment]
@jonathanolson Confirmed on master (tested on Build a Fraction Lab screen)

**Comment by KatieWoe** [comment]
1.0.0-rc.2 looks clear
