### ISSUE TITLE
Equality Lab Firefox Issues

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/fractions-common#81]
**Test Device:**
Magnus
**OS:**
10.11.6
**Browser:**
Firefox 64.0.2
**Problem Description:**
For https://github.com/phetsims/QA/issues/260 when on the equality lab screen of Fractions: Equality the denominator can be changed to seven and zero. When holding down the arrow key to increase the denominator, the denominator will increase past six to seven, likewise for decreasing past one to zero. The sim will continue to function properly and there are no issues with moving "1/7" pieces around, however if the denominator goes to zero the sim will break, and nothing can be manipulated. The major issue concerns having the denominator go to zero where the sim breaks. It should be noted that both the up and down arrow are greyed out at the respective values of six and one, showing that the denominator should not be able to be manipulated further in whichever direction is greyed out. I haven't been able to find exact conditions to reproduce so simply decrease and increase the denominator by holding the button for a couple of seconds until the issue has occurred. It seems to happen most often when the sim has just been launched or reloaded. I have attached a screenshot of the sim when the denominator is seven and zero for reference. In the console there are no errors thrown when the denominator is seven, but an unexpected value matrix of (NaN) alert is given when the denominator is zero.
![screen shot 2019-01-24 at 12 07 35 pm](https://user-images.githubusercontent.com/30352536/51702818-06409600-1fd2-11e9-903f-27d3d8ef6a4f.png)
 
![screen shot 2019-01-24 at 11 55 28 am](https://user-images.githubusercontent.com/30352536/51701599-03907180-1fcf-11e9-866b-ae31cd88c0fc.png)

**Comment by KatieWoe** [comment]
Have managed to reproduce 10.14.3 firefox.  Only just after refreshing and after while it got harder, possibly due to caching.  Did not have the grayed out buttons, but I may have misunderstood the steps.

**Comment by KatieWoe** [comment]
Haven't reproduced using similar tools in the other sims, but I wouldn't necessarily rule it out.

**Comment by ariel-phet** [comment]
@jonathanolson this seemed difficult to reproduce and rare (I watched @KatieWoe)

This bug is definitely not a showstopper for 1.0. If it is an easy fix (in the 10 or 15 minute range) feel free to fix. If not, please mark deferred and we will fix after 1.0 is published.

**Comment by KatieWoe** [comment]
Replicated at least once on Win 10 firefox.

**Comment by jonathanolson** [comment]
Added a patch that should hopefully prevent this (and pushed it to the RC branches).

@KatieWoe can you see if this makes it impossible for the given bug to occur?

**Comment by KatieWoe** [comment]
1.0.0-rc.2 unable to reproduce on this version.  Will still keep an eye out for it and would like @JRomero0613 to take a look if he has the chance, since I was unable to reproduce some of the effects he saw.

**Comment by amanda-phet** [comment]
@KatieWoe since QA testing is done, can this issue be closed?
