### ISSUE TITLE
Edge browser: parts of sim disappear briefly

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#83]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Edge
**Problem description:**
Found on https://github.com/phetsims/QA/issues/269.  Behavior was similar to https://github.com/phetsims/energy-forms-and-changes/issues/203.
May be in the other three sims as well.
When playing Level 3 building shapes in the Build a Fraction game screen, a large chunk of the middle of the screen turned the light blue of the background.  This happened as I was dragging the first piece into a shape building container.  It lasted a few seconds before returning to normal.  Recreating the steps doesn't seem to reproduce.
**Steps to reproduce:**
Seems to be tied to normal play randomly

Troubleshooting information (do not edit):

<details>

Name: ‪Build a Fraction‬
URL: https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-rc.2/phet/build-a-fraction_en_phet.html
Version: 1.0.0-rc.2 2019-01-25 20:40:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This is happening in https://github.com/phetsims/QA/issues/294

**Comment by KatieWoe** [comment]
For Fraction Matcher dev test, I'm not sure if its the background color, the frequency, the fact I haven't seen the bug in awhile, or what, but it seems more jarring and almost headache inducing there.

**Comment by ariel-phet** [comment]
@KatieWoe can you retest this on the dev version of Edge? If it is fixed, can you mark this issue `wontfix` and close. If it is still present, please reassign to me.

**Comment by KatieWoe** [comment]
@ariel-phet did a pretty long check of Build a Fraction, and a shorter check of Fraction Matcher.  Didn't see anything on Dev Edge.  However, I also did a quick check of both on published Edge and didn't really see it there either.  Not sure what's going on there.  Up to you if you want to close.

**Comment by ariel-phet** [comment]
@KatieWoe closing
