### ISSUE TITLE
Can I adjust matcher target equals sign positions?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#86]
The old (and current) behavior for the targets has the equals sign in the center of the targets:

<img width="594" alt="screen shot 2019-02-21 at 10 45 42 am" src="https://user-images.githubusercontent.com/480878/53190015-fd89b280-35c5-11e9-9611-530ec244e27d.png">

I'd prefer to have the equals sign be centered between the two fraction pieces (same padding on the left and right). Would that be acceptable?

**Comment by jonathanolson** [comment]
(So the equals sign would shift slightly towards the numeric fractions in general, since they are less wide)

**Comment by amanda-phet** [comment]
I agree that would look better.

**Comment by jonathanolson** [comment]
Implemented above, should now look like:

<img width="684" alt="screen shot 2019-02-21 at 11 23 24 am" src="https://user-images.githubusercontent.com/480878/53192287-53ad2480-35cb-11e9-9f5e-d2e722d804ca.png">

**Comment by amanda-phet** [comment]
I like it! 

I think that since these equations aren't stacked vertically, you don't even notice the alignment of the equal sign.
