### ISSUE TITLE
Improve layout of matching pieces on scales

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-common#87]
Certain representations don't sit well:

<img width="246" alt="screen shot 2019-02-21 at 1 01 35 pm" src="https://user-images.githubusercontent.com/480878/53198122-df797d80-35d8-11e9-90b1-3a271404199d.png">

So there probably needs to either be a "rest on the bottom of bounds", or custom offsets for each.

**Comment by jonathanolson** [comment]
Based off the bottom of the bounds generally works well, although cases like this might need tweaks:

<img width="222" alt="screen shot 2019-02-21 at 1 25 52 pm" src="https://user-images.githubusercontent.com/480878/53199420-4482a280-35dc-11e9-87b7-e5b49a9ae825.png">

**Comment by jonathanolson** [comment]
https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.8/phet/fraction-matcher_en_phet.html shows the new scale positioning.

@ariel-phet and @amanda-phet how does this look?

**Comment by amanda-phet** [comment]
Aligning the base of the shapes is looking good to me. The only odd case I noticed is this one, beacuse the shape hangs off the sides a bit. In particular on the right. But I don't think a vertical shift would help, and am fine with this case, just wanted to document it. It's about getting the idea that the shape is on a scale, and this still works. 

<img width="155" alt="screen shot 2019-02-28 at 1 06 11 pm" src="https://user-images.githubusercontent.com/7852916/53595193-dbf67100-3b59-11e9-9475-3c482d1aeace.png">

**Comment by amanda-phet** [comment]
@ariel-phet feel free to close if it looks good to you.

**Comment by ariel-phet** [comment]
Current state on Master is looking pretty good. Closing
