### ISSUE TITLE
Reset All does not reset points, time, or levels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#90]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/294
Hitting the orange reset all button only resets the sound and activation of the timer.  Nothing else is reset.
**Steps to reproduce:**
1. Complete a level with time activated
2. Go into another level to examine the set up (what pieces are there) and leave
3. Hit reset all on that page
4. Turn on timer again to note that points and time are still there
5. Go into the level from step 2 and note that level is still the same

**Screenshots:**
![notreset](https://user-images.githubusercontent.com/41024075/53897679-e4d0c200-3ff3-11e9-8e41-1b7494f218a7.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fraction Matcher‬
URL: https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.10/phet/fraction-matcher_all_phet.html
Version: 1.2.0-dev.10 2019-03-05 17:13:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
Should be fixed in master, can you verify?

**Comment by KatieWoe** [comment]
This does seem fixed on master @jonathanolson

**Comment by jonathanolson** [comment]
Thanks!
