### ISSUE TITLE
Your new best message given when time is worse

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#91]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/294
After beating a level with timer on it seems that it will always read "Your new best" under the time, even when the time is worse than a previous attempt.
**Steps to reproduce:**
1. Turn the timer on
2. Select a level and beat it in a reasonable time
3. Select the same level and wait a minute before starting so the time will be worse
4. Beat the level and note the message
5. Upon leaving note that the previous record is still there.

**Screenshots:**
![notmybest](https://user-images.githubusercontent.com/41024075/53899209-eb146d80-3ff6-11e9-9a4c-ac6ffee39f4d.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fraction Matcher‬
URL: https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.10/phet/fraction-matcher_all_phet.html
Version: 1.2.0-dev.10 2019-03-05 17:13:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
This should be fixed. @KatieWoe can you verify?

**Comment by KatieWoe** [comment]
The above issue is solved in master.  However, I noticed that hitting the reset all button doesn't wipe the previous record in the blue victory dialog.  It resets in the level select screen, but if you get a worse time in a level after reset all, the blue dialog treats it as if the old record still stands.
![victorydoesntreset](https://user-images.githubusercontent.com/41024075/56606621-e0706080-65c3-11e9-8dd0-21606ed227f6.gif)

**Comment by jonathanolson** [comment]
Nice find! I believe the above patch should fix that, can you verify?

**Comment by KatieWoe** [comment]
@jonathanolson Looks good.  Didn't see any problems on master.

**Comment by jonathanolson** [comment]
Thanks!
