### ISSUE TITLE
Back arrow and refresh button clickable when dialog up

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#93]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/294
When the end of dialog is up, normally any buttons behind are made unclickable.  This is not the case here as you can hit the back arrow and the refresh button.  This can lead to an odd connected bug.  When you click the continue button and return to the level you have a new setup and can play again.  If you hit the back button then come back the dialog is gone, and all the pieces are in the answer boxes.  You need to hit the refresh level button to start again.  The timer is also counting up if it is on.
**Steps to reproduce:**
1. Beat a level
2. Hit continue
3. Go back to that level and observe setup
4. Go to a different level and beat it
5. Hit the back arrow instead of continue
6. Go back to that level and observe setup

**Screenshots:**
![backarrow](https://user-images.githubusercontent.com/41024075/53910765-e4472400-4011-11e9-8633-322e6b01a0f8.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Fraction Matcher‬
URL: https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.10/phet/fraction-matcher_all_phet.html
Version: 1.2.0-dev.10 2019-03-05 17:13:31 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
Checked for a good example to work from. expression-exchange actually has clickable buttons in front:

<img width="1300" alt="Screen Shot 2019-04-02 at 12 22 52 PM" src="https://user-images.githubusercontent.com/480878/55426448-0fa22d80-5542-11e9-8b11-139d3fde33f5.png">

Area Model and BCE seem to remove the content behind when showing the reward.

@amanda-phet or @ariel-phet, should we consider one of those approaches instead? The code for LevelCompletedNode isn't well set up to be modal (and you'd probably want to gray out a background if that was done).

**Comment by amanda-phet** [comment]
This seems consistent with the other game screens (see https://github.com/phetsims/fractions-common/issues/7 for extra context).

**Comment by amanda-phet** [comment]
@KatieWoe can you do a comparison of this game and the build-a-fraction style games? I think in the BAF games, you can click back, but you can later return to a completed level and not lose your work. In FM games, you click back, but if you return to a level your progress is cleared.

**Comment by KatieWoe** [comment]
It does behave as you describe in BAF games.  I brought this issue up because the published version disables the back button in this situation.

**Comment by amanda-phet** [comment]
Since this seems to be consistent with fractions-common I am OK with the behavior as it is. 

@jonathanolson I agree that in ExEx the button layering makes more sense, so if you can move the buttons in front of the reward node I think that will work well.

**Comment by ariel-phet** [comment]
+1 for going with the ExEx button layering if possible.

**Comment by jonathanolson** [comment]
The reward now should be in the background, and the timer will stop increasing once all of the targets are filled.

Something that seems a bit inconsistent (which I'd like to resolve, but I'm not sure what is best): If you hit "continue" after completing a level, visiting the same level afterwards shows a regenerated challenge. However if you just hit the "return" button, visiting the same level will show the same (completed) challenge.

How ideally should this behave?

**Comment by phet-steele** [comment]
> How ideally should this behave?

It would be a HECK of a lot more consistent with other PhET games of this type, and with the published version, to show a regenerated challenge upon return to a level.

**Comment by KatieWoe** [comment]
@jonathanolson this behavior looks rather off to me.  I'd like @amanda-phet to weigh in on it before moving on with it.
![fallingbehind](https://user-images.githubusercontent.com/41024075/56605475-7f478d80-65c1-11e9-996b-3ca7a51d4528.gif)

**Comment by amanda-phet** [comment]
I agree with @KatieWoe that it looks a little strange, especially since the stuff layered in front isn't all interactive. But I think having the buttons layered in front (since they are interactive) is a priority. @ariel-phet ideas here? 

>Something that seems a bit inconsistent (which I'd like to resolve, but I'm not sure what is best): If you hit "continue" after completing a level, visiting the same level afterwards shows a regenerated challenge. However if you just hit the "return" button, visiting the same level will show the same (completed) challenge.

This is not good. Whether you hit continue or back, then return to the level, the level should show a refreshed set of challenges. This is most consistent with all other games of this [type](https://docs.google.com/document/d/14BNBrokYt1OI2Y7lzjhkAP2aSnEfBh7xBW868ss2spg/edit).

**Comment by jonathanolson** [comment]
> I agree with @KatieWoe that it looks a little strange, especially since the stuff layered in front isn't all interactive.

It does look a bit strange, but is also consistent with Expression Exchange (reward is behind all of the collection areas).

> This is most consistent with all other games of this type.

The code responsible seems to control all games of this type (A.5?)

I'll have it force refreshing of the challenge when opening it.

**Comment by jonathanolson** [comment]
Back button will now also refresh a fully-completed challenge.

Anything else to do here?

**Comment by amanda-phet** [comment]
I don't think so! Thank you!
