### ISSUE TITLE
Should this be title case or sentence case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#94]
From https://github.com/phetsims/QA/issues/294
Discussed with @amanda-phet on slack.  Headings on game screens tend to be inconsistent across sims.  Should this be adressed?  How?

Arithmetic 
![titlecasearithmetic](https://user-images.githubusercontent.com/41024075/53915882-0d6db180-401e-11e9-807a-636966740fa9.jpg)
Graphing Lines
![titlecasegraphinglines](https://user-images.githubusercontent.com/41024075/53915906-1a8aa080-401e-11e9-915e-04800ec5e72d.jpg)
Fraction Matcher
![titlecasefractionmatcher](https://user-images.githubusercontent.com/41024075/53916014-56256a80-401e-11e9-8424-293615a2a955.jpg)
Build a Fraction
![titlecasebuildafraction](https://user-images.githubusercontent.com/41024075/53916033-62a9c300-401e-11e9-88f0-636c172e1ee3.jpg)

**Comment by amanda-phet** [comment]
These should be title case (Choose Your Level!). 

I just reviewed a number of games and the majority use title case, so that should be our standard. 

@jonathanolson can you change the casing for all of the game screens, even though Fraction Matcher is the only one being republished right now?

**Comment by jonathanolson** [comment]
Area Model doesn't have a title prompt. Should it have one for consistency?

**Comment by jonathanolson** [comment]
Equality Explorer has "Solve for x" (uncapitalized 'for'). Should that change?

**Comment by jonathanolson** [comment]
Checked over everything else with level-selection screens to make sure things were capitalized correctly (with the above questions as the only exceptions).

**Comment by amanda-phet** [comment]
I meant all game screens in fractions-common. I can make a separate issue for area-model-common. 

Thanks!
