### ISSUE TITLE
Two is displayed as 2 0/3

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#95]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/294
On the published version of Fraction Matcher, the number two is displayed as 2.  In the dev version it is displayed as 2 0/3 or something similar.  This does not cause any problems with completing the level, but it looks quite odd.
**Steps to reproduce:**
1. Go to the Mixed Number screen
2. Go to level 4
3. If piece in question is not there, hit the refresh level button until it appears

**Screenshots:**
Dev:
![oddlook](https://user-images.githubusercontent.com/41024075/53919124-4873e300-4026-11e9-8afe-f89c56ed0e75.jpg)
Published:
![published](https://user-images.githubusercontent.com/41024075/53919135-50338780-4026-11e9-95fd-963231435b80.jpg)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Fraction Matcher‬
URL: https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.10/phet/fraction-matcher_all_phet.html
Version: 1.2.0-dev.10 2019-03-05 17:13:31 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by amanda-phet** [comment]
We should not be showing the fraction if 0 is in the numerator.

**Comment by lmulhall-phet** [comment]
I've seen the number 1 being displayed as 1/1 in 1.2.0-dev.10.

**Comment by jonathanolson** [comment]
Should be displayed without the (0/x) on the "mixed" screens, and displayed as an improper fraction (e.g. 1/1, 2/1) on the "unmixed" screens.

**Comment by jonathanolson** [comment]
I believe this is fixed in the above commit, can you verify?

**Comment by KatieWoe** [comment]
@jonathanolson so for clarification, does that mean that https://github.com/phetsims/fractions-common/issues/95#issuecomment-470324237 is not a bug?

**Comment by jonathanolson** [comment]
I believe so. @amanda-phet can you verify?

**Comment by KatieWoe** [comment]
It looks like what @jonathanolson describes on master.  @amanda-phet to confirm if this is the desired behavior.

**Comment by amanda-phet** [comment]
Both screens in Fraction Matcher look correct to me. Thanks for finding and fixing this!
