### ISSUE TITLE
Possible Issue with show answers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#96]
For https://github.com/phetsims/QA/issues/294
While playing the sim on IE, I got a question wrong twice, but hitting the show answer button did nothing.  I was unable to drag any pieces either.  The button looked depressed, but didn't trigger any action.  I haven't been able to reproduce so far, so I don't know if it was IE specific or not.

**Comment by KatieWoe** [comment]
Linking to https://github.com/phetsims/fractions-common/issues/98 and https://github.com/phetsims/fractions-common/issues/99

**Comment by KatieWoe** [comment]
Had this happen in google chrome, so not platform specific.  Seems to be random when it happens

**Comment by jonathanolson** [comment]
Likely resolved by https://github.com/phetsims/fractions-common/issues/99.

**Comment by KatieWoe** [comment]
They seem to be duplicates, so I'm unassigning and closing
