### ISSUE TITLE
Mute button doesn't carry over

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-common#97]
For https://github.com/phetsims/QA/issues/294
When you press the mute button on the published Fraction Matcher it is muted (or unmuted) on both pages.  In the dev test it only effects the page it is pressed on.  This second behavior is the behavior of the timer button in both versions.
![soundthing](https://user-images.githubusercontent.com/41024075/53922034-0059be00-4030-11e9-9fb8-f3d1fe7a11c2.gif)

**Comment by amanda-phet** [comment]
@KatieWoe what is the question?

**Comment by KatieWoe** [comment]
Should the status of mute/unmute carry over between screens?  Should the timer?

**Comment by amanda-phet** [comment]
Seems to me that the buttons would be screen-specific, and if we wanted something for the entire sim we'd have that mute button in the nav bar. 

I bet you're thinking it would make sense that if someone wants sound off, they want it off on both screens, but I'd prefer to use a better universal control for that. 

@ariel-phet is the navbar sound control only an option for some sims?

**Comment by ariel-phet** [comment]
@amanda-phet I think that sound control in the navbar can be used in any sim (but has only been used in sims with sounds for a11y so far so those often also have the "enhanced" sound option in the menu). I would be fine with it being used here. That may require one minor change (converting this sim to Tambo from Vibe if not already done). Your call.

**Comment by jonathanolson** [comment]
Looks like the plan is for @jbphet to move GameAudioPlayer over to tambo. I'll be available to assist.

**Comment by jonathanolson** [comment]
@jbphet took care of the main work today, and I switched things over on the sim side. This removes all of the sound buttons from the fractions suite, replaced with the navbar button.
