### ISSUE TITLE
Smiley Face When Both Attempts Wrong

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/fractions-common#98]
For https://github.com/phetsims/QA/issues/294.

Seen on Windows 10 + FF, but it happens on other platforms.

Happens on both screens.

**Comment by KatieWoe** [comment]
Good catch @lmulhall-phet 
Here is a clip showing this happen:
![smiles](https://user-images.githubusercontent.com/41024075/53969047-50c72f00-40b5-11e9-8773-038b42f0880b.gif)
No smiley shows up in this case on the published version

**Comment by jonathanolson** [comment]
Should be fixed in master, can you verify?

**Comment by KatieWoe** [comment]
Looks fixed on master

**Comment by jonathanolson** [comment]
Thanks!
