### ISSUE TITLE
Nothing Happens When Show Answer Button Clicked

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/fractions-common#99]
For https://github.com/phetsims/QA/issues/294.

Seen on Windows 10 + Edge.

I got this to happen by repeatedly putting in wrong answers. At one point the Show Answers button could be clicked, but nothing happened.

When this happens, the fractions are not clickable.

**Comment by KatieWoe** [comment]
Linking to https://github.com/phetsims/fractions-common/issues/96

**Comment by KatieWoe** [comment]
Had this happen in google chrome, so not platform specific.  Seems to be random when it happens

**Comment by KatieWoe** [comment]
Happens on a Mac as well, so not just Windows

**Comment by jonathanolson** [comment]
Should be fixed in master. Do you feel it is best to proactively check this, or just see if it happens during the next other testing?

**Comment by KatieWoe** [comment]
I can check on master, but since it was semi random as to when it happened it should still be checked in the next round of testing, just in case it slips through somehow.

**Comment by jonathanolson** [comment]
For reference, the bug that I know happened was when the piece that would stay on a scale (e.g. 1/2) and all the "matching" pieces below are different multiples (e.g. 2/4 below). It used the improper equality check, so it wouldn't pull out the 2/4 up to the scale.

**Comment by KatieWoe** [comment]
That's great.  Thanks for the clarification

**Comment by KatieWoe** [comment]
The issue as described seems solved on master.  It should still be looked out for in the next round of testing in case there was an extra cause of some kind.

**Comment by jonathanolson** [comment]
Sounds good, marking as fixed-pending-testing.

**Comment by KatieWoe** [comment]
This looks good in rc.1

**Comment by jonathanolson** [comment]
Ok sounds good, closing then. Thanks!
